
# Gereric info
input_file: '/home/jingxiao/BLASYS_PART/adder/adder.v'
testbench: '/home/jingxiao/BLASYS_PART/adder/adder_tb.v'
toplevel: 'adder'
err_thresh: 0.50
output_dir: 'output'
debug: true
parallel_processing: false

# Partitioner Variable
lsoracle_path: 'lstools'
partition_count: 40

partitioned_file: '/home/jingxiao/blasys_private/benchmarks/adder32/adder32_parts.v'
k_string: '33333333'

# Library Information
liberty_file: '/home/jingxiao/blasys_private/asap7.lib'

# Synthesis
yosys_path: 'yosys'

# Simulation
iverilog_path: 'iverilog'
vvp_path: 'vvp'
error_metric: 'binary'
