
# LSOracle for partitioning
lsoracle: '/home/jingxiao/new_lsoracle/LSOracle/build/core/lsoracle'

# Synthesis
yosys: 'yosys'

# Simulation
iverilog: 'iverilog'
vvp: 'vvp'

# ABC for synthesis
abc: 'abc'

# OpenSTA for delay and power analysis
OpenSTA: 'sta'
